##**Objective:**
WAP to implement the Perceptron Learning Algorithm using numpy in Python. Evaluate performance of a single perceptron for NAND and XOR truth tables as input dataset.

##**Description of the Model:**
- This is a single-layer perceptron model implemented using numpy.
- It uses a step activation function (threshold function) and is trained using
the perceptron learning rule. The model attempts to learn the NAND and XOR functions.

##**Python Implementation**

In [8]:
import numpy as np
from sklearn.metrics import confusion_matrix

class Perceptron:
    def __init__(self, input_size, lr=0.1, epochs=100):
        self.weights = np.random.randn(input_size + 1)  # Including bias
        self.lr = lr
        self.epochs = epochs

    def activation(self, x):
        return 1 if x >= 0 else 0

    def predict(self, x):
        x = np.insert(x, 0, 1)  # Adding bias term
        return self.activation(np.dot(self.weights, x))

    def train(self, X, y):
        for _ in range(self.epochs):
            for xi, target in zip(X, y):
                xi = np.insert(xi, 0, 1)  # Adding bias term
                pred = self.activation(np.dot(self.weights, xi))
                error = target - pred
                self.weights += self.lr * error * xi  # Update weights

    def evaluate(self, X, y):
        predictions = [self.predict(x) for x in X]
        correct = sum(p == t for p, t in zip(predictions, y))
        accuracy = correct / len(y) * 100
        print(f'Accuracy: {accuracy:.2f}%')

        # Compute confusion matrix
        cm = confusion_matrix(y, predictions)
        print("Confusion Matrix:")
        print(cm)
        return cm

# NAND Truth Table
X_nand = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_nand = np.array([1, 1, 1, 0])

# XOR Truth Table
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([0, 1, 1, 0])

# Train Perceptron on NAND
print("Training Perceptron for NAND")
nand_perceptron = Perceptron(input_size=2, lr=0.1, epochs=100)
nand_perceptron.train(X_nand, y_nand)
nand_perceptron.evaluate(X_nand, y_nand)

# Train Perceptron on XOR
print("\nTraining Perceptron for XOR")
xor_perceptron = Perceptron(input_size=2, lr=0.1, epochs=100)
xor_perceptron.train(X_xor, y_xor)
xor_perceptron.evaluate(X_xor, y_xor)


Training Perceptron for NAND
Accuracy: 100.00%
Confusion Matrix:
[[1 0]
 [0 3]]

Training Perceptron for XOR
Accuracy: 50.00%
Confusion Matrix:
[[1 1]
 [1 1]]


array([[1, 1],
       [1, 1]])

##**Code Explanation:**
- `Perceptron class:` Implements the perceptron learning algorithm.
- `train method:` Updates weights using the perceptron learning rule.
- `predict method:` Uses the step activation function to classify inputs.
- `evaluate method:` Computes accuracy.

##**My Comments:**
1. The perceptron works well for NAND as it is a linearly separable problem.
2. The model fails for XOR since it is not linearly separable, meaning a single-layer perceptron
   cannot find a proper decision boundary.
3. To learn XOR, a multi-layer perceptron (MLP) with a hidden layer and non-linear activation
   (like sigmoid or ReLU) is needed.
4. The training process could be improved by adding dynamic learning rates or momentum.
5. The weight initialization could be refined to avoid slow convergence.